# Aula 01

In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(0, 10) # ou np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.eye(4) # matriz identidade

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.linspace(0, 10, 2) # especifica a quantidade de números espaçados

array([ 0., 10.])

In [14]:
np.random.rand(5) # segue distribuição uniforme entre 0 e 1

array([0.04455257, 0.23823043, 0.11257727, 0.6416395 , 0.03925867])

In [15]:
np.random.rand(5) * 100

array([89.90868016, 90.71449957, 89.3462692 , 46.31167974, 81.3841352 ])

In [16]:
np.random.rand(5, 4)

array([[0.69001572, 0.42529249, 0.38771185, 0.61983251],
       [0.97394484, 0.81293633, 0.24488431, 0.16539597],
       [0.79163591, 0.94714679, 0.78427539, 0.5213281 ],
       [0.21839071, 0.38680736, 0.6944607 , 0.42064287],
       [0.11648564, 0.19247922, 0.97471349, 0.54498679]])

In [17]:
np.random.rand(5, 4, 3) # tridimensional

array([[[0.5511841 , 0.75053703, 0.50293544],
        [0.25505374, 0.50266672, 0.15901897],
        [0.69205408, 0.42217084, 0.30004749],
        [0.31450957, 0.93621447, 0.28203261]],

       [[0.55713463, 0.32881623, 0.79653522],
        [0.0337422 , 0.35317665, 0.93339816],
        [0.59554778, 0.50698272, 0.79266713],
        [0.71885013, 0.55636232, 0.34150723]],

       [[0.85797197, 0.49853126, 0.44749627],
        [0.17931992, 0.81486811, 0.96033421],
        [0.02711652, 0.00896491, 0.79269816],
        [0.15367518, 0.68389086, 0.86202441]],

       [[0.09422586, 0.21801998, 0.49094621],
        [0.97609137, 0.82105478, 0.16071021],
        [0.1990783 , 0.72940151, 0.7650478 ],
        [0.61530773, 0.15192461, 0.34248048]],

       [[0.97696893, 0.86721714, 0.91463685],
        [0.0210643 , 0.29918036, 0.1924608 ],
        [0.09959175, 0.92680637, 0.50281474],
        [0.95792211, 0.65589829, 0.6217693 ]]])

In [18]:
np.random.randn(4) # distribuição normal (gaussiana)

array([ 0.31215574,  0.58389922, -0.24774542,  0.55749391])

In [19]:
np.random.randint(0, 100, 10) # 10 valores entre 0 e 100 aleatórios

array([44, 18, 46, 28, 22, 32, 57, 15, 82, 55])

In [20]:
np.round(np.random.rand(5) * 100, 0) # mesmo que o randint

array([81., 81., 98., 40., 15.])

In [21]:
np.random.rand(25).reshape((5, 5)) # transforma em uma matriz 5x5

array([[0.21878885, 0.93941059, 0.69382435, 0.82197997, 0.57852708],
       [0.67908584, 0.99759486, 0.15644649, 0.5543387 , 0.54349062],
       [0.75745315, 0.36938417, 0.96066823, 0.50256595, 0.87435826],
       [0.85829632, 0.986373  , 0.58664689, 0.73424256, 0.80410835],
       [0.4741712 , 0.13768861, 0.58916295, 0.07508837, 0.98788619]])

In [24]:
np.shape([[1, 3, 4], [3, 4, 6]]) # exibe a dimensão da matriz | se fosse (2,) seria um vetor

(2, 3)

In [25]:
np.max([3, 4, 5, 9, 2])

9

In [26]:
np.min([2, 5, 2, 1, 5])

1

In [30]:
np.argmax([2, 3, 9, 2, 3]) # retorna a posição de menor valor

2

In [31]:
np.argmin([7, 3, 2, 4, 1]) # retorna a posição de maior valor

4

# Aula 02

In [32]:
array = np.arange(0, 30, 3)

In [34]:
array[2:5] # retorna os elementos 2, 3 e 4 (excetua o quinto elemento)

array([ 6,  9, 12])

In [35]:
array[:5] # todos os elementos até a posição 4

array([ 0,  3,  6,  9, 12])

In [36]:
array[2:] # todos os elementos a partir da posição 2

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [38]:
bidimensional = np.arange(50).reshape((5, 10))

In [39]:
bidimensional

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
bidimensional[:3] # retorna as 3 primeiras linhas

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [45]:
 bidimensional[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [50]:
copia = bidimensional[:3].copy()

In [51]:
copia

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [52]:
copia[:] = 100 # substitui todos os valores de cada elemento

In [53]:
copia

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [55]:
copia[0:4, 5:]  # arr[rows, columns]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [58]:
booleano = bidimensional > 30

In [59]:
booleano

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [60]:
bidimensional[booleano] # retorna os valores que são True na condição do booleano

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [61]:
busca = np.linspace(0, 100, 30)

In [62]:
busca

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [64]:
nova_busca = busca.reshape(3, 10)

In [65]:
nova_busca

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [69]:
nova_busca[0:2, 2] # retorna os elementos da segunda posição presentes nas linhas 0 e 1

array([ 6.89655172, 41.37931034])

# Aula 03

In [72]:
arr = np.arange(16)

In [73]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [74]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [76]:
arr / arr

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [80]:
arr[arr > 0] / arr[1:] # solução que implementei para excluir o zero da divisão

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
arr ** arr

array([                 1,                  1,                  4,
                       27,                256,               3125,
                    46656,             823543,           16777216,
                387420489,        10000000000,       285311670611,
            8916100448256,    302875106592253,  11112006825558016,
       437893890380859375])

In [82]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [83]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85])

In [84]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500])

In [85]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15])

In [86]:
np.sqrt(arr) # raiz quadrada

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [87]:
np.exp(arr) # exponenciação

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [88]:
np.mean(arr) # média

7.5

In [89]:
np.std(arr) # desvio padrão

4.6097722286464435

In [90]:
np.sin(arr) # seno

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

# Exercícios

In [92]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
np.arange(10).sum()

45

In [98]:
matrix = np.arange(9).reshape(3, 3)

In [99]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
matrix.sum(axis=0) # soma colunas

array([ 9, 12, 15])

In [101]:
matrix.sum(axis=1) # soma linhas

array([ 3, 12, 21])